worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include mime.types;
    default_type text/plain;

    # 自定义日志格式
    log_format main '$remote_addr - [$time_local] '
                    '"$request" $status $body_bytes_sent '
                    '"$http_referer" "$http_user_agent" '
                    'rt=$request_time';

    
    gzip on;
    gzip_types text/plain text/css application/javascript image/jpeg image/png;
    gzip_min_length 1024;
    gzip_comp_level 5;
    gzip_vary on;

    #输出到标准输出、错误，方便docker日志收集、排障
    access_log /dev/stdout main;
    error_log /dev/stderr warn;

    server {
        listen 80;
        server_name _;

        location / {
           proxy_pass http://netdisk_app:5000;
           proxy_set_header Host $host;
           proxy_set_header X-Real-IP $remote_addr;
           proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
           proxy_set_header X-Forwarded-Proto $scheme;

           proxy_connect_timeout 5s;
           proxy_send_timeout 10s;
           proxy_read_timeout 10s;
        }

        # 静态资源：关闭日志，减少磁盘写入
        location /static/ {
            alias /app/static/;
            expires 30d;
            add_header Cache-Control "public,no-transform";
            access_log off;
        }

        # 健康检查：也关闭日志，否则每几秒写一条，全是垃圾
        location = /health {
            access_log off;
            return 200 "ok";
        }
    }
}
